name 'darin-susefw'
version '0.1'
source 'git://github.com/deadpoint/susefw.git'
author 'Darin Perusich'
license 'Apache 2.0'
summary 'SuSEfirewall2 module'
description 'SuSEfirewall2 module'
project_page 'https://github.com/deadpoint/susefw'
dependency 'puppetlabs/stdlib', '>= 2.2.1'

